/**
 * 
 * Generated by
 * 
     ______                _____             
    |  ____|              |  __ \            
    | |__   __ _ ___ _   _| |  | | _____   __
    |  __| / _` / __| | | | |  | |/ _ \ \ / /
    | |___| (_| \__ \ |_| | |__| |  __/\ V / 
    |______\__,_|___/\__, |_____/ \___| \_/  
                      __/ |                  
   	  						   |___/  
 *                 
 *			www.easydev.org
 */


//IMPORT PROPERTY
const properties = require('./properties.js');

//IMPORT LIBRARY
const logger = require('./logger.js');
const express = require('express');
const app = module.exports = express();
const mongoose = require('mongoose');
const extend = require('extend');
const http = require('http');
const bodyParser = require('body-parser');

// START IMPORT DB

require('./db/tombola_db_crud.js');
// END IMPORT DB

//ADD PARSE
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

//IMPORT SECURITY & RESOURCES
require('./security/security.js');
require('./security/securityMapping.js');

//START APPLICATION
const server = http.Server(app);
app.use(express.static(properties.publicPath));

server.listen(properties.port, function() {
    logger.info('listening on *:' + properties.port);
});
